feat: logic
IoT-MHWS/hs-server pull request #12
Opened 2023-10-18 16:26 UTC by thermvs

2023-10-18 20:27 UTC, niqzart reviewed
Я тут чутка накидал, а по существу всё гуд. Много, правда, тестить, но разберусь))

2023-10-18 20:27 UTC, niqzart commented on src/main/java/artgallery/hsserver/controller/ArtistController.java
> +@RequestMapping("/api/v1/artist")
Если по rest, то artists (именно множественное)

2023-10-18 20:27 UTC, niqzart commented on src/main/java/artgallery/hsserver/controller/ArtistController.java
> +  @GetMapping("/all")
Если по рест, то без all, прост слеш

2023-10-18 20:27 UTC, niqzart commented on src/main/java/artgallery/hsserver/controller/ArtistController.java
> +  private static class ArtistValidator extends Validator {
А можно несколько классов в одном файле и за это не бьют?))0)

2023-10-18 20:27 UTC, niqzart commented on src/main/java/artgallery/hsserver/controller/ArtistController.java
> +@RequestMapping("/api/v1/artist")
Ну думаю понятно, что я к тому, что надо везде так, если мы хотим, чтобы не придрались))

2023-10-18 20:27 UTC, niqzart commented on src/main/java/artgallery/hsserver/controller/TicketController.java
> +      }
Хм, а что это за id и зачем оно в валидаторе?

2023-10-19 06:44 UTC, zubrailx commented on src/main/java/artgallery/hsserver/controller/ArtistController.java
> +  private static class ArtistValidator extends Validator {
нет, он статический вложенный @niqzart

2023-10-19 07:19 UTC, zubrailx requested changes

2023-10-19 07:19 UTC, zubrailx commented on src/main/java/artgallery/hsserver/service/OrderService.java
> +  public OrderDTO createOrder(OrderDTO orderDTO) throws UserDoesNotExistException, TicketDoesNotExistException {
Добавить `@Transactiona`

2023-10-19 07:19 UTC, zubrailx commented on src/main/java/artgallery/hsserver/service/OrderService.java
> +  public void deleteOrder(long id) throws OrderDoesNotExistException {
Добавить `@Transactiona`

2023-10-19 07:19 UTC, zubrailx commented on src/main/java/artgallery/hsserver/service/PaintingService.java
> +  public PaintingDTO createPainting(PaintingDTO paintingDTO) throws ArtistDoesNotExistException, GalleryDoesNotExistException {
Добавить `@Transactional`

2023-10-19 07:19 UTC, zubrailx commented on src/main/java/artgallery/hsserver/service/PaintingService.java
> +      //-----
Поубирай черточки здесь, выше и ниже

2023-10-19 07:19 UTC, zubrailx commented on src/main/java/artgallery/hsserver/service/TicketService.java
> +  public TicketDTO createTicket(TicketDTO ticketDTO) throws ExhibitionDoesNotExistException, OrderDoesNotExistException {
`@Transactional`

2023-10-19 07:19 UTC, zubrailx commented on src/main/java/artgallery/hsserver/service/TicketService.java
> +  public TicketDTO updateTicket(long id, TicketDTO ticketDTO) throws TicketDoesNotExistException, ExhibitionDoesNotExistException {
`@Transactional`

2023-10-19 07:19 UTC, zubrailx commented on src/main/java/artgallery/hsserver/service/TicketService.java
> +      new ExhibitionDoesNotExistException(ticketDto.getExhibitionId()));
Не обращайся в мапперах к бд, лучше передай в качестве аргумента. Не заметишь - сломаешь транзакционность. Тем более не кидай отсюда вообще бдшные ошибки

2023-10-19 07:19 UTC, zubrailx commented on src/main/java/artgallery/hsserver/service/TicketService.java
> +  public void deleteTicket(long id) throws TicketDoesNotExistException {
`@Transactional`

2023-10-19 07:19 UTC, zubrailx commented on src/main/java/artgallery/hsserver/service/PaintingService.java
> +      new ArtistDoesNotExistException(paintingDTO.getArtistId()));
Не обращайся в мапперах к бд, лучше передай в качестве аргумента. Не заметишь - сломаешь транзакционность. Тем более не кидай отсюда вообще бдшные ошибки

2023-10-19 07:19 UTC, zubrailx commented on src/main/java/artgallery/hsserver/service/OrderService.java
> +    List<TicketEntity> ticketEntities = ticketRepository.findAllById(ticketIds);
Не обращайся в мапперах к бд, лучше передай в качестве аргумента. Не заметишь - сломаешь транзакционность. Тем более не кидай отсюда вообще бдшные ошибки

2023-10-19 07:19 UTC, zubrailx commented on src/main/java/artgallery/hsserver/service/GalleryService.java
> +    gallery.setGalleryPaintings(galleryPaintingEntities);
Не обращайся в мапперах к бд, лучше передай в качестве аргумента. Не заметишь - сломаешь транзакционность. Тем более не кидай отсюда вообще бдшные ошибки

2023-10-19 07:19 UTC, zubrailx commented on src/main/java/artgallery/hsserver/service/ExhibitionService.java
> +      new GalleryDoesNotExistException(exhibitionDTO.getGalleryId()));
Не обращайся в мапперах к бд, лучше передай в качестве аргумента. Не заметишь - сломаешь транзакционность. Тем более не кидай отсюда вообще бдшные ошибки

2023-10-19 08:03 UTC, niqzart commented on src/main/java/artgallery/hsserver/controller/ArtistController.java
> +  private static class ArtistValidator extends Validator {
java такая правильно неправильная

2023-10-19 08:06 UTC, niqzart commented on src/main/java/artgallery/hsserver/controller/ArtistController.java
> +    headers.add("Artists-Count", String.valueOf(artistsPage.getTotalElements()));
> Должен быть минимум один запрос, который вернет findAll с пагинацией и с указанием общего количества записей в **http хедере**

Криво, да, но требования реально такие ¯\_(ツ)_/¯

2023-10-19 08:30 UTC, zubrailx commented on src/main/java/artgallery/hsserver/controller/ArtistController.java
> +    headers.add("Artists-Count", String.valueOf(artistsPage.getTotalElements()));
Реально? Кринжатина

2023-10-19 15:23 UTC, merged