feat: split creation and connection of entities to simplify api
IoT-MHWS/hs-server pull request #20
Opened 2023-10-26 17:35 UTC by thermvs

2023-10-31 13:40 UTC, niqzart requested changes

2023-10-31 13:40 UTC, niqzart commented on src/main/java/artgallery/hsserver/controller/GalleryController.java
> +  }
Всё таки думаю POST не нужен, а то ещё заставят пояснить, что это + 409 нужно выкидывать

2023-10-31 13:40 UTC, niqzart commented on src/main/java/artgallery/hsserver/controller/GalleryController.java
> +      boolean isNewLink = (galleryService.getLinkByGalleryIdAndPaintingId(galleryId, paintingId).isEmpty());
Можно сделать `existsBy...` в репозитории, и прокинуть через сервис сразу boolean

2023-10-31 13:40 UTC, niqzart commented on src/main/java/artgallery/hsserver/controller/PaintingController.java
> +  }
Писал, что делать маппинг в обе стороны бессмыслено, если логика сайта (которого нет) не требудет такого. Надо бы выбрать, у нас картины в галлереях или галлереии в картинах и оставить одно

2023-10-31 13:40 UTC, niqzart commented on src/main/java/artgallery/hsserver/model/GalleryEntity.java
> +//  private List<GalleryPaintingEntity> galleryPaintings;
А что случилось с отношением на уровне БД? Или оно тип не используется, поэтому убрано?

2023-10-31 13:40 UTC, niqzart commented on src/main/java/artgallery/hsserver/service/GalleryService.java
> +      .orElseThrow(() -> new PaintingDoesNotExistException(paintingId));
Красивое

2023-10-31 13:40 UTC, niqzart commented on src/main/java/artgallery/hsserver/service/GalleryService.java
> +  public GalleryPaintingDTO createOrUpdateLinkGalleryToPainting(long galleryId, long paintingId, DescriptionDTO linkDto, boolean isNewLink)
`@Transactional`? Кажется не только тут

2023-10-31 13:40 UTC, niqzart commented on src/main/java/artgallery/hsserver/controller/PaintingController.java
> +  }
В Service там вообще копирование кода пошло, даже для джавы не очень выглядит уже. Я прост боюсь, что он к такому может докопаться

2023-11-01 09:39 UTC, thermvs commented on src/main/java/artgallery/hsserver/controller/PaintingController.java
> +  }
Можно посмотреть картины в выбранной галерее, и галереи, в которых выставляется картина. Мне кажется, можно оставить оба варианта

2023-11-02 09:41 UTC, niqzart approved these changes
Красивое

2023-11-02 09:47 UTC, merged